services:
  api:
    build:
      context: .
      dockerfile: PagueVeloz.Challenge.Api/Dockerfile
    ports:
      - "8080:80" 
      # - "8081:443" 
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development 
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - db_data:/app/data

volumes:
  db_data: